%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Medium Length Professional CV
%
% Original author:
% Gajjala Sreekanthreddy
%
% Important note:
% This template requires the resume.cls file to be in the same directory as the
% .tex file. The resume.cls file provides the resume style used for structuring the
% document.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%----------------------------------------------------------------------------------------
%	PACKAGES AND OTHER DOCUMENT CONFIGURATIONS
%----------------------------------------------------------------------------------------

\documentclass{resume} % Use the custom resume.cls style

\usepackage[left=0.75in,top=0.6in,right=0.75in,bottom=0.6in]{geometry} % Document margins
\newcommand{\tab}[1]{\hspace{.2667\textwidth}\rlap{#1}}
\newcommand{\itab}[1]{\hspace{0em}\rlap{#1}}
\name{Gajjala Sreekanthreddy} % Your name
\address{R.No - 402, Gowthami PG Boys hostel, JNTU Campus, KPHB, Hyderabad} % Your address
%\address{123 Pleasant Lane \\ City, State 12345} % Your secondary addess (optional)
\address{(+91) 9550915619 \\ gajjalasreekanthreddy2018@gmail.com} % Your phone number and email


\begin{document}


\begin{rSection}{Career Objective}
To pursue a challenging career and be a part of progressive organization that gives a scope to enhance my knowledge and utilizing my skills towards the growth of the organization.
\end{rSection}
%----------------------------------------------------------------------------------------
%	EDUCATION SECTION
%----------------------------------------------------------------------------------------

\begin{rSection}{Education}
{\bf JNTU Hyderabad, Telangana} \hfill {\em Jul 2018 - Jun 2020} 
\\ Master of Science  \hfill {\em Pursuing} 
\\ Information Technology\\
\\{\bf Shri Mata Vaishno Devi University, Jammu} \hfill {\em Aug 2014 - May 2018} 
\\ Bachelor of Technology  \hfill {\em GPA 5.93/10} 
\\ Dept. of Electronics and Communication Engineering\\
\\{\bf Narayana Junior College, YSR Kadapa} \hfill {\em June 2011 - April 2013} 
\\ 12th Class, PCM\hfill { \em Overall Percentage: 95.6 }\\
\\{\bf Ravindra Bharathi School, YSR Kadapa} \hfill {\em April 2010 - April 2011} 
\\ 10th Class, PCM\hfill { \em Overall Percentage: 95 }
%Minor in Linguistics \smallskip \\
%Member of Eta Kappa Nu \\
%Member of Upsilon Pi Epsilon \\


\end{rSection}

%----------------------------------------------------------------------------------------
%	WORK EXPERIENCE SECTION
%----------------------------------------------------------------------------------------

\begin{rSection}{Internships}

\begin{rSubsection}{Data Centre, Mankind Pharma Limited }{Dec 2017 – June 2018}{Intern - Graduate Trainee Engineer(Systems)}{On Site Internship}
Real Time Application of IT Operations such as \\
-	Windows Server 2012 R2 \\
-	Trouble shooting the Desktops, PCs on the network through Remote Access Control  \\
-	LAN/WAN Management, IT Support \\
-	Creating RAID (Risks, Assumptions, Issues and Dependencies) log before any project \\
-	Experience in backup tool NetBackup, Troubleshooting Hardware and Operating system related issue.\\ 
-	Experience with OS, Installation, Upgrades and Patching\\
-	Troubleshooting & Implementation experience in WAN protocols & service providers \\
\end{rSubsection}

\begin{rSubsection}{J&K Power Development Department }{May 2017 – July 2017}{Intern - Systems Engineering}{On Site Internship}
-Desktop support\\
-LAN/WAN Management\\
-Trouble shooting PCs and other hardware.\\
\end{rSubsection}
\end{rSection}
\pagebreak
%--------------------------------------------------------------------------------
%  TECHNICAL SKILLS
%----------------------------------------------------------------------------------------
\begin{rSection}{Technical Skills}
\begin{tabular}{ @{} >{\bfseries}l @{\hspace{6ex}} l }
Programming Languages \ & C, Java \\
Data Bases  \ & SQL \\
Web Technologies \ & HTML, CSS, Java Script\\
Tools \ & MS Office, Latex \\
Operating Systems \ & Windows Server 2012 R2, Windows(7,8,10,XP), Cent OS \\
\end{tabular}

\end{rSection}
%--------------------------------------------------------------------------------
%    Projects And Seminars
%-----------------------------------------------------------------------------------------------
\begin{rSection}{Projects}
{\bf Major(MSIT): (March 2019 – April 2019) }
\\E-commerce pharmacy store Web application using- \\Angular JS, JavaScript, Node JS, Express JS, HTML, CSS\\
Platform : Visual Studio Code, Node JS \\
Data Base : MongoDB\\

\\{\bf Major(Internship): (Dec 2017 – June 2018) }
\\Implementation and Validation of Master-Slave Digital clock systems and synchronization of workstations, digital clock systems and instruments with NTP Server. \\



\end{rSection}

%----------------------------------------------------------------------------------------
%	LANGUAGES
%----------------------------------------------------------------------------------------
\begin{rSection}{Languages Known}
\\Telugu : Mother Tongue\\
Hindi: Fluent\\
English: Fluent\\
\end{rSection}
\\
\\

%----------------------------------------------------------------------------------------
% FIELD OF INTEREST
%----------------------------------------------------------------------------------------
\begin{rSection}{Fields of Interest} 
Cloud Computing, IT Administration, DBMS, Computer Networks, IT Operations
\end{rSection}
%	EXAMPLE SECTION
%----------------------------------------------------------------------------------------

\begin{rSection}{Activities and appreciations} 
- Received an award in TITIKSHA 2015 Annual Technical Fest for standing 2nd position in ROBO RACE Contest.\\ 
- Received certificate of participation cum training from i3indya Technologies in VisionBotics. \\
- Received a Letter of Appreciation from International Volunteer Foundation for participating in Swach Bharat Abhiyan - Swach Vaishno Devi Shrine 2015 \\

\end{rSection}
\begin{rSection}{related works}
Designed and developed a website for JS Institute of Medical College - https://www.jsims.in/ \\
Github: https://github.com/gajjala-sreekanthreddy/
\end{rSection}

\begin{rSection}{Personal Traits}
Ability to learn quickly and work in harmony with co-workers\\
Technical Competency\\
Adaptability and problem solving skills\\
\end{rSection}

\begin{flushleft}
Date : 16 th April 2019\\
Place : JNTU, Hyderabad
\end{flushleft}
\begin{flushright}
Gajjala Sreekanthreddy
\end{flushright}
\end{document}
